/*
 * ================================================================================================
 *  WARNING: This file is automatically generated by cbindgen. Manual edits are likely to be lost.
 * ================================================================================================
 */

#ifndef LAKERS_EAD_AUTHZ_H
#define LAKERS_EAD_AUTHZ_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define EAD_AUTHZ_LABEL 1

#define EAD_AUTHZ_INFO_K_1_LABEL 0

#define EAD_AUTHZ_INFO_IV_1_LABEL 1

#define EAD_AUTHZ_ENC_STRUCTURE_LEN ((2 + 8) + 3)

typedef struct ZeroTouchDevice {
  EdhocMessageBuffer id_u;
  BytesP256ElemLen g_w;
  EdhocMessageBuffer loc_w;
} ZeroTouchDevice;

typedef struct ZeroTouchDeviceWaitEAD2 {
  BytesHashLen prk;
  BytesHashLen h_message_1;
} ZeroTouchDeviceWaitEAD2;

typedef struct ZeroTouchDeviceDone {
  BytesMac voucher;
} ZeroTouchDeviceDone;

#endif /* LAKERS_EAD_AUTHZ_H */
